# Generated by Django 4.1.7 on 2023-03-29 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_uuid_token_userlocation_useravatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid_token',
        ),
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(default=uuid.UUID('6e90c8c9-f9ce-46e9-82b4-56d845e32cc1'), max_length=255),
        ),
    ]
